language: node_js
node_js: 
 - 'node'
env:
  - PROJECT=thesaurus-widget
notifications:
  email:
    - axel.verstappen@gmail.com
    - cedrik.vanderhaegen@vlaanderen.be
sudo: required
services:
  - xvfb
addons:
  chrome: stable
install:
  - (cd ./ && npm install)
script:
  - (cd ./ && npm test)
