language: node_js
node_js:
 - 14
env:
  - PROJECT=thesaurus-widget
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_install:
  - nvm install 14.19.3
  - npm install -g yarn
install:
  - yarn install
before_script:
  - "export DISPLAY=:99.0"
script:
  - yarn test
