language: node_js
node_js: 
 - 'node'
env:
  - PROJECT=thesaurus-widget
notifications:
  email:
    - axel.verstappen@gmail.com
#sudo: required
addons:
  chrome: stable --no-sandbox
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - (cd ./ && npm install)
script:
  - (cd ./ && npm test)
