language: node_js
node_js: 
 - 'node'
env:
  - PROJECT=thesaurus-widget
sudo: required
services:
  - xvfb
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
before_install:
  - nvm install 11.2.0
  - nvm use 11.2.0
install:
  - (cd ./ && npm install)
script:
  - (cd ./ && npm test)
